---
name: CI

# yamllint disable-line rule:truthy
on:
#   push:
#   pull_request:
#     types:
#       - opened
#       - reopened
#       - synchronize
  workflow_dispatch:
  
jobs:
  information:
    name: Gather add-on information
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.information.outputs.architectures }}
      build: ${{ steps.information.outputs.build }}
      description: ${{ steps.information.outputs.description }}
      name: ${{ steps.information.outputs.name }}
      slug: ${{ steps.information.outputs.slug }}
      target: ${{ steps.information.outputs.target }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: 🚀 Run add-on information action
        id: information
        uses: frenck/action-addon-information@v1.0.0

  lint-addon:
    name: Lint Add-on
    needs:
      - information
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: 🚀 Run Add-on Lint
        uses: frenck/action-addon-linter@v1.3.1
        with:
          path: "./${{ needs.information.outputs.target }}"
